# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    expor login -u $(EXPO_USERNAME) -p $(EXPO_PASSWORD)
  displayName: 'Inicio sesion en expo CLI'

- script: |
    expo build:android -t apk  # Compilar el APK
    displayName: 'Compilar APK de Android con Expo'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './dist'  # Cambia esta ruta si necesitas que sea más específica
    ArtifactName: 'apk'  # Nombre del artefacto publicado
  displayName: 'Publicar el APK como artefacto'
