# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'Default'  # Nombre del pool donde está tu agente autoalojado
  demands:
    - Agent.OS -equals Windows_NT

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g eas-cli  # Instala EAS CLI
    npm ci  # Instala dependencias del proyecto
  displayName: 'Instalar dependencias y EAS CLI'

  # 3. Autenticarse en Expo con token (o con usuario y contraseña)
- script: |
    eas login --token $(EXPO_TOKEN)  # Usar token Expo
  displayName: 'Iniciar sesión en Expo con token'
  env:
    EXPO_TOKEN: $(EXPO_TOKEN)  # Token almacenado como variable secreta en Azure DevOps

  # 4. Ejecutar la compilación de EAS para Android (usando el perfil de producción)
- script: |
     eas build --platform android --profile production --non-interactive
  displayName: 'Compilar APK de Android con EAS'
  
  # 5. Publicar el APK como artefacto
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'builds'  # Ruta del APK generado por EAS
    ArtifactName: 'apk'
    publishLocation: 'Container'
  displayName: 'Publicar APK como artefacto'