# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'Default'  # Nombre del pool donde est치 tu agente autoalojado
  demands:
    - Agent.OS -equals Windows_NT

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g eas-cli
    npm ci  
  displayName: 'Instalar dependencias y EAS CLI'
  
- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install NPM'

  # 3. Autenticarse en Expo con token (o con usuario y contrase침a)
- script: |
      eas build --platform android --profile production --non-interactive
  displayName: 'Compilar APK de Android con EAS'
  env:
    EXPO_TOKEN: $(EXPO_TOKEN)
  
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: "single"
    artifactName: 'apk'
    targetPath: '$(Build.SourcesDirectory)/builds'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'app-center'  # La conexi칩n de servicio a App Center configurada en Azure DevOps
    appSlug: 'ucompesar/React-Expo'  # Ajustar con el owner y el nombre de la app en App Center
    symbolsOption: 'Android'
    apk: '$(Build.SourcesDirectory)/builds/**/*.apk'  # Ruta del APK generado por EAS
    releaseNotesOption: 'input'
    releaseNotesInput: 'Nueva versi칩n Android compilada desde Azure DevOps'
    destinationType: 'groups'